v13.3

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -307,7 +307,7 @@ jobs:
             dast-report.json
             dast-report.html
 
-  # ---------- Image Scan ----------
+# ---------- Image Scan ----------
   image-scan:
     runs-on: ubuntu-latest
     needs: build
@@ -336,17 +336,6 @@ jobs:
       - name: Pull image for scanning
         run: docker pull ${{ secrets.YC_REGISTRY_REPO }}:${{ needs.build.outputs.image_tag }}
 
-      - name: Debug Trivy (top CRITICAL)
-        if: always()
-        run: |
-          if [ -s image-scan-reports/trivy-image.sarif ]; then
-            echo "Top CRITICAL from Trivy:"
-            jq -r '.runs[]?.results[]? | select(.level=="error") |
-                   [.ruleId, (.message?.text // ""), (.locations[0]?.physicalLocation?.artifactLocation?.uri // "")] | @tsv' \
-              image-scan-reports/trivy-image.sarif | head -n 30 || true
-          fi
-      
-
       - name: Trivy image scan (SARIF)
         uses: aquasecurity/trivy-action@0.24.0
         with:
@@ -355,11 +344,22 @@ jobs:
           output: trivy-image.sarif
           severity: CRITICAL
           ignore-unfixed: true
-          scanners: vuln
-          vuln-type: library
+          scanners: vuln           # только уязвимости
+          vuln-type: library       # только либы (без ОС, misconfig)
+          args: --exit-code 0      # экшен не валит шаг (гейт решает)
         continue-on-error: true
-      
-      
+
+      - name: Show CRITICAL (debug)
+        if: always()
+        run: |
+          if [ -s trivy-image.sarif ]; then
+            echo "Top CRITICAL from Trivy:"
+            jq -r '.runs[]?.results[]? | select(.level=="error")
+                    | [.ruleId, (.message?.text // ""), (.locations[0]?.physicalLocation?.artifactLocation?.uri // "")]
+                    | @tsv' trivy-image.sarif | head -n 50 || true
+          else
+            echo "trivy-image.sarif is empty or missing"
+          fi
 
       - name: Upload Trivy SARIF
         if: always()
@@ -372,6 +372,7 @@ jobs:
         with:
           name: image-scan-reports
           path: trivy-image.sarif
+  
 
   # ---------- Security Gateway ----------
   security-gateway:
